### ISSUE TITLE
stdin?

### ISSUE THREAD

**Issue by zkat** [lewiscowper/markdown-chalk#25]
it would be awesome to be able to use this with stdin: `npx awesome-npx | npx markdown-chalk --input --` or something.

**Comment by lewiscowper** [comment]
@zkat Sorry for missing this for so long. Yes, I think that'd be awesome. It's currently very hard coded to read from a file, but I'd be happy for PRs related to this, and failing that I'll get to it at some point soon-ish and explore how to handle stdin input :) :+1:

Thanks for creating this :)
